spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type 
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
  
# User Service routing configuration
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

# Movie Service routing configuration
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
            
# Rating Service routing configuration
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**

              
              
              
server:
  port: 9004
  
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  